/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.GenericGenerator;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import java.io.Serializable;

/**
 * @author dzni0816
 */
@Entity
@Getter
@Setter
@Transactional
public class ProductItems implements Serializable {

    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(
            name = "UUID",
            strategy = "org.hibernate.id.UUIDGenerator"
    )
    private String id;

    @Basic
    private Float mp;

    @Basic
    private Float otp;

    @Basic
    private Float MPWithTaxandDiscont;

    @Basic
    private Float OTPWithTaxandDiscont;

    @ManyToOne(targetEntity = Soproduct.class)
    private Soproduct soproduct;

    @ManyToOne(targetEntity = OrdItem.class, cascade = CascadeType.REMOVE)
    private OrdItem ordItem;
}
