/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Getter
@Setter
public class CustomerDto implements Serializable {

    private String id;
    private String firstName;
    private String lastName;
    private String contact;
    private String email;
    private String phone;
    private String userId;
    private String username;
    private String passNumber;
    private String countNumber;
    private String location;
    private AddressDto address1;
    private List<LocationDto> locations;
    private List<RelatedLocationDto> relatedLocations;
    private List<StatisticsCollectorDto> statisticscollectors;
    private List<SoDto> soes;

}
