/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Getter
@Setter
public class Customer implements Serializable {

    private String id;
    private String firstName;
    private String lastName;
    private String contact;
    private String email;
    private String phone;
    private String userId;
    private String username;
    private String passNumber;
    private String countNumber;
    private String location;
    private Address address1;
    private List<Location> locations;
    private List<RelatedLocation> relatedLocations;
    private List<Statisticscollector> statisticscollectors;
    private List<So> soes;

}
