/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Getter
@Setter
public class DiscountRuleDto implements Serializable {

    private String id;
    private Float discountValue;
    private Float discountProcent;
    private String type;
    private String description;
    private List<ItemDiscountDto> itemdiscounts;
    private List<OrdItemDiscountDto> orditemdiscounts;

}
