/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Getter
@Setter
public class Groups implements Serializable {

    private String id;
    private String name;
    private List<Itemgroup> itemgroups1;

}
