/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import java.io.Serializable;

/**
 * @author dzni0816
 */
@Getter
@Setter
public class Itemgroup implements Serializable {

    private String id;
    private Groups groups1;
    private Item item1;

}
