/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import java.io.Serializable;

/**
 * @author dzni0816
 */
@Getter
@Setter
public class ItemGroupDto implements Serializable {

    private String id;
    private GroupsDto groups1;
    private ItemDto item1;

}
