/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * @author dzni0816
 */

@Getter
@Setter
public class Item implements Serializable {

    private String id;
    private String name;
    private String type;
    private String description;
    private Float defMP;
    private Float defOTP;
    private String modifiedDate;
    private BigInteger quantity;
    private Item parent;
    private List<Item> items = new ArrayList<>();
    private List<ItemLocations> itemlocations;

//    @OneToMany(targetEntity = ProductItems.class, mappedBy = "item1")
//    private List<ProductItems> productItemses1;

    private List<Itemgroup> itemgroups1;
    private List<Itemdiscount> itemdiscounts1;
    private List<ItemCharacteristic> itemCharacteristic;

}
