/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * @author dzni0816
 */

@Getter
@Setter
public class ItemDto implements Serializable {

    private String id;
    private String name;
    private String type;
    private String description;
    private Float defMP;
    private Float defOTP;
    private String modifiedDate;
    private BigInteger quantity;
    private ItemDto parent;
    private List<ItemDto> items = new ArrayList<>();
    private List<ItemLocationsDto> itemlocations;

//    @OneToMany(targetEntity = ProductItemsDto.class, mappedBy = "item1")
//    private List<ProductItemsDto> productItemses1;

    private List<ItemGroupDto> itemgroups1;
    private List<ItemDiscountDto> itemdiscounts1;
    private List<ItemCharacteristicDto> itemCharacteristic;

}
