/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Getter
@Setter
public class Paymentbill implements Serializable {

    private String id;
    private Float cmp;
    private Float cotp;
    private Float cMPDisc;
    private Float cOTPDisc;
    private List<Payment> payments;
}
