/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import java.io.Serializable;
import java.util.Date;

/**
 * @author dzni0816
 */
@Getter
@Setter
public class Payment implements Serializable {

    private String id;
    private String paymentInfo;
    private Date paymentDate;
    private Paymenttype paymenttype;
    private So so;
    private Paymentbill paymentbill;

}
