/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Getter
@Setter
public class Paymenttype implements Serializable {

    private String id;
    private String typeName;
    private List<Payment> payments;
}
