/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import java.io.Serializable;

/**
 * @author dzni0816
 */
@Getter
@Setter
public class ProductItems implements Serializable {

    private String id;
    private Float mp;
    private Float otp;
    private Float MPWithTaxandDiscont;
    private Float OTPWithTaxandDiscont;
    private Soproduct soproduct;
    private OrdItem ordItem;
}
