/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

/**
 * @author dzni0816
 */
@Getter
@Setter
public class SoDto implements Serializable {

    private String id;
    private String dateCreated;
    private String orderDate;
    private String status;
    private String SONumber;
    private String purchaseOrderNumber;
    private String dateModified;
    private BigDecimal finalMP;
    private BigDecimal finalOTP;
    private BigDecimal finalMPwithTaxAndDiscount;
    private BigDecimal finalOTPwithTaxAndDiscount;
    private String distributionChannel;
    private String attentionFlag;
    private CustomerDto customer;
    private List<PaymentDto> payments;
    private List<SoProductDto> soproducts;
    private LocationDto location;
}
