/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import java.io.Serializable;

/**
 * @author dzni0816
 */
@Getter
@Setter
public class Statisticscollector implements Serializable {

    private String id;
    private String statisticType;
    private String statisticsInfo;
    private Customer customer;

}
