server:
  port: 8083

spring:
  liquibase:
    enabled: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default-schema: demo
    generate-ddl: false
    database: POSTGRESQL
    show-sql: true
#    hibernate:
#      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
#    url: jdbc:postgresql://be4x0r1rfffinvjf8mmp-postgresql.services.clever-cloud.com:5432/be4x0r1rfffinvjf8mmp
#    username: uu1dezf1kkx5qbm2higq
#    password: t1uhQnH0Q69DVsfzzmO1
    url: jdbc:postgresql://ec2-52-200-119-0.compute-1.amazonaws.com:5432/d1777nfj3b7552
    username: dyqupsknurzetl
    password: 32cb635675d62b16c66047a648af137e39cd284fa804fc72bd990e2be41403bd
    driver-class-name: org.postgresql.Driver
