server:
  port: 8083
  servlet:
    context-path: /api

spring:
  liquibase:
    enabled: false
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default-schema: demo
    generate-ddl: false
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-174-129-29-101.compute-1.amazonaws.com:5432/dcorjq5gogu8np
    username: vievzjyolsohyh
    password: d57bce07c83051b8eeb6a67259c0798def2c1b86b2e7930978ae7dd6989955af
    driver-class-name: org.postgresql.Driver
