server:
  port: 8083
  servlet:
    context-path: /api

spring:
  liquibase:
    enabled: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default-schema: demo
    generate-ddl: false
    database: POSTGRESQL
    show-sql: true
#    hibernate:
#      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://be4x0r1rfffinvjf8mmp-postgresql.services.clever-cloud.com:5432/be4x0r1rfffinvjf8mmp
    username: uu1dezf1kkx5qbm2higq
    password: t1uhQnH0Q69DVsfzzmO1
    driver-class-name: org.postgresql.Driver
