server:
  port: 8083
  servlet:
    context-path: /api

spring:
  liquibase:
    enabled: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default-schema: demo
    generate-ddl: false
    database: POSTGRESQL
    show-sql: true
#    hibernate:
#      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-174-129-227-80.compute-1.amazonaws.com:5432/d5urp5bhm69i67
    username: dmcaqwlqggngag
    password: 99b6b983cb6d1ec9e01e4aad215027824c7d999d65796b87df81a6f6c89f3e27
    driver-class-name: org.postgresql.Driver
