/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Proxy;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * @author dzni0816
 */

@Entity
@Proxy(lazy = false)
@Getter
@Setter
@Transactional
public class Item implements Serializable {

    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(
            name = "UUID",
            strategy = "org.hibernate.id.UUIDGenerator"
    )
    private String id;

    @Basic
    private String name;

    @Basic
    private String type;

    @Basic
    private String description;

    @Basic
    private Float defMP;

    @Basic
    private Float defOTP;

    @Basic
    private String modifiedDate;

    @Basic
    private BigInteger quantity;

    @ManyToOne(targetEntity = Item.class)
    private Item parent;

    @OneToMany(targetEntity = Item.class, mappedBy = "parent", cascade = {CascadeType.REMOVE, CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.EAGER)
    private List<Item> items = new ArrayList<>();

    @OneToMany(targetEntity = ItemLocations.class, mappedBy = "item", cascade = CascadeType.REMOVE)
    private List<ItemLocations> itemlocations;

//    @OneToMany(targetEntity = ProductItems.class, mappedBy = "item1")
//    private List<ProductItems> productItemses1;

    @OneToMany(targetEntity = Itemgroup.class, mappedBy = "item1", cascade = CascadeType.REMOVE)
    private List<Itemgroup> itemgroups1;

    @OneToMany(targetEntity = Itemdiscount.class, mappedBy = "item1", cascade = CascadeType.REMOVE)
    private List<Itemdiscount> itemdiscounts1;

    @OneToMany(targetEntity = ItemCharacteristic.class, mappedBy = "item", cascade = CascadeType.REMOVE)
    private List<ItemCharacteristic> itemCharacteristic;

}
