/**
 * This file was generated by the JPA Modeler
 */
package com.example.demo.model;

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.GenericGenerator;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import java.io.Serializable;
import java.util.Date;

/**
 * @author dzni0816
 */
@Entity
@Getter
@Setter
@Transactional
public class Payment implements Serializable {

    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(
            name = "UUID",
            strategy = "org.hibernate.id.UUIDGenerator"
    )
    private String id;

    @Basic
    private String paymentInfo;

    @Basic
    private Date paymentDate;

    @ManyToOne(targetEntity = Paymenttype.class)
    private Paymenttype paymenttype;

    @ManyToOne(targetEntity = So.class)
    private So so;

    @ManyToOne(targetEntity = Paymentbill.class)
    private Paymentbill paymentbill;

}
